### ISSUE TITLE
Static files create broken links sometimes

### ISSUE THREAD

**Issue by prowlett** [chirun-ncl/chirun#54]
Static files within sub-parts do not make proper links, in two ways. I think this is because, while a static link within a file uses `/static/...` and works, creating a link relative to the root of the current course site, putting the same link in `config.yml` does not work - it creates a link relative to the web server root. So I am putting links like `static/...` in `config.yml` so that they work. However, this causes problems.

As a minimal example, here is a course `config.yml`. 

```
title: "Test module"
year: 2020/21
structure: 
    - type: introduction
      leading_text: hello
      source: index.md
    - type: part
      title: A part
      content:
        - type: url
          title: Static file 1
          source: static/files/file1.docx
        - type: part
          title: A sub-part
          content:
            - type: url
              title: Static file 2
              source: static/files/file2.docx
themes: 
  - title: Default
    source: default
    path: default
build_pdf: True
```

(The `introduction` is there because of issue #49.)

Both file1.docx and file2.docx are copied across to `build/default/static/files/`.

In `build/default/index.html`: Static file 1 creates an anchor tag `<a target="_blank" href="static/files/file1.docx">Static file 1</a>` which works fine.

In `build/default/a_part/index.html`: Static file 1 creates an anchor tag `<a target="_blank" href="static/files/file1.docx">Static file 1</a>` i.e. pointing to `build/default/a_part/static/files/file1.docx`, which is not a file.

In `build/default/a_part/a_subpart/index.html`: Static file 2 creates an anchor tag `<a target="_blank" href="static/files/file2.docx">Static file 2</a>` i.e. pointing to `build/default/a_part/a_subpart/static/files/file2.docx`, which is not a file.
